package mod.kagic.init;

import net.minecraft.util.ResourceLocation;
import net.minecraft.util.SoundEvent;
import net.minecraftforge.event.RegistryEvent;

public class ModSounds {
	public static final SoundEvent RECORD_LITTLE_PERIDOT = new SoundEvent(new ResourceLocation("ndbkagic:records.little_peridot"));
	public static final SoundEvent RECORD_ROSES_FOUNTAIN = new SoundEvent(new ResourceLocation("ndbkagic:records.roses_fountain"));
	public static final SoundEvent RECORD_LAPIS_FLIGHT = new SoundEvent(new ResourceLocation("ndbkagic:records.lapis_flight"));
	public static final SoundEvent RECORD_THE_BREAKING_POINT = new SoundEvent(new ResourceLocation("ndbkagic:records.the_breaking_point"));
	public static final SoundEvent RECORD_DUEL_OF_THE_QUARTZ = new SoundEvent(new ResourceLocation("ndbkagic:records.duel_of_the_quartz"));
	public static final SoundEvent RECORD_YELLOW_DIAMOND = new SoundEvent(new ResourceLocation("ndbkagic:records.yellow_diamond"));
	public static final SoundEvent RECORD_BLUE_DIAMOND = new SoundEvent(new ResourceLocation("ndbkagic:records.blue_diamond"));
	public static final SoundEvent RECORD_WHATS_THE_USE_OF_FEELING_BLUE = new SoundEvent(new ResourceLocation("ndbkagic:records.whats_the_use_of_feeling_blue"));
	public static final SoundEvent RECORD_LOVE_LIKE_YOU = new SoundEvent(new ResourceLocation("ndbkagic:records.love_like_you"));

	public static final SoundEvent RECORD_HEAVEN_BEETLE = new SoundEvent(new ResourceLocation("ndbkagic:records.heaven_beetle"));
	public static final SoundEvent RECORD_DEFECTIVE = new SoundEvent(new ResourceLocation("ndbkagic:records.defective"));
	public static final SoundEvent RECORD_GEM_SHARDS = new SoundEvent(new ResourceLocation("ndbkagic:records.gem_shards"));
	public static final SoundEvent RECORD_HEART_OF_THE_PYRAMID = new SoundEvent(new ResourceLocation("ndbkagic:records.pyramid"));
	public static final SoundEvent RECORD_UNDERWATER_TEMPLE = new SoundEvent(new ResourceLocation("ndbkagic:records.underwater_temple"));

	public static final SoundEvent BLOCK_GEM_SEED_HATCH = new SoundEvent(new ResourceLocation("ndbkagic:blocks.gem_seed_hatch"));
	public static final SoundEvent BLOCK_INJECTOR_OPEN = new SoundEvent(new ResourceLocation("ndbkagic:blocks.injector_open"));
	public static final SoundEvent BLOCK_INJECTOR_CLOSE = new SoundEvent(new ResourceLocation("ndbkagic:blocks.injector_close"));
	public static final SoundEvent BLOCK_INJECTOR_FIRE = new SoundEvent(new ResourceLocation("ndbkagic:blocks.injector_fire"));
	public static final SoundEvent GEM_POOF = new SoundEvent(new ResourceLocation("ndbkagic:entities.gem.poof"));
	public static final SoundEvent GEM_SHATTER = new SoundEvent(new ResourceLocation("ndbkagic:entities.gem.shatter"));
	
	public static final SoundEvent SLAG_EAT = new SoundEvent(new ResourceLocation("ndbkagic:entities.slag.eat"));
	public static final SoundEvent SLAG_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.slag.living"));
	public static final SoundEvent PEPO_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.pepo.living"));
	public static final SoundEvent RUBY_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.living"));
	public static final SoundEvent RUBY_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.hurt"));
	public static final SoundEvent RUBY_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.obey"));
	public static final SoundEvent RUBY_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.death"));
	public static final SoundEvent RUBY_EXPLODE = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.explode"));
	public static final SoundEvent RUBY_COMBINE = new SoundEvent(new ResourceLocation("ndbkagic:entities.ruby.combine"));
	public static final SoundEvent SAPPHIRE_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.sapphire.living"));
	public static final SoundEvent SAPPHIRE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.sapphire.hurt"));
	public static final SoundEvent SAPPHIRE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.sapphire.obey"));
	public static final SoundEvent SAPPHIRE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.sapphire.death"));
	public static final SoundEvent PADPARADSCHA_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.padparadscha.living"));
	public static final SoundEvent PERIDOT_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.peridot.living"));
	public static final SoundEvent PERIDOT_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.peridot.hurt"));
	public static final SoundEvent PERIDOT_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.peridot.obey"));
	public static final SoundEvent PERIDOT_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.peridot.death"));
	public static final SoundEvent PEARL_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.pearl.hurt"));
	public static final SoundEvent PEARL_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.pearl.obey"));
	public static final SoundEvent PEARL_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.pearl.death"));
	public static final SoundEvent PEARL_SING = new SoundEvent(new ResourceLocation("ndbkagic:entities.pearl.sing"));
	public static final SoundEvent PEARL_WEIRD = new SoundEvent(new ResourceLocation("ndbkagic:entities.pearl.weird"));
	public static final SoundEvent BISMUTH_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.bismuth.hurt"));
	public static final SoundEvent BISMUTH_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.bismuth.obey"));
	public static final SoundEvent BISMUTH_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.bismuth.death"));
	public static final SoundEvent JASPER_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.jasper.hurt"));
	public static final SoundEvent JASPER_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.jasper.obey"));
	public static final SoundEvent JASPER_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.jasper.death"));
	public static final SoundEvent AMETHYST_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.amethyst.hurt"));
	public static final SoundEvent AMETHYST_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.amethyst.obey"));
	public static final SoundEvent AMETHYST_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.amethyst.death"));
	public static final SoundEvent ROSE_QUARTZ_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.rose_quartz.hurt"));
	public static final SoundEvent ROSE_QUARTZ_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.rose_quartz.obey"));
	public static final SoundEvent ROSE_QUARTZ_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.rose_quartz.death"));
	public static final SoundEvent CARNELIAN_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.carnelian.hurt"));
	public static final SoundEvent CARNELIAN_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.carnelian.obey"));
	public static final SoundEvent CARNELIAN_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.carnelian.death"));
	public static final SoundEvent LAPIS_LAZULI_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.lapis_lazuli.hurt"));
	public static final SoundEvent LAPIS_LAZULI_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.lapis_lazuli.obey"));
	public static final SoundEvent LAPIS_LAZULI_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.lapis_lazuli.death"));
	public static final SoundEvent AGATE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.agate.hurt"));
	public static final SoundEvent AGATE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.agate.obey"));
	public static final SoundEvent AGATE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.agate.death"));
	public static final SoundEvent YELLOW_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("ndbkagic:entities.yellow_diamond.intro"));
	public static final SoundEvent YELLOW_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("ndbkagic:entities.yellow_diamond.outro"));
	public static final SoundEvent YELLOW_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.yellow_diamond.living"));
	public static final SoundEvent YELLOW_DIAMOND_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.yellow_diamond.hurt"));
	public static final SoundEvent YELLOW_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.yellow_diamond.death"));
	public static final SoundEvent BLUE_DIAMOND_INTRO = new SoundEvent(new ResourceLocation("ndbkagic:entities.blue_diamond.intro"));
	public static final SoundEvent BLUE_DIAMOND_OUTRO = new SoundEvent(new ResourceLocation("ndbkagic:entities.blue_diamond.outro"));
	public static final SoundEvent BLUE_DIAMOND_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.blue_diamond.living"));
	public static final SoundEvent BLUE_DIAMOND_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.blue_diamond.hurt"));
	public static final SoundEvent BLUE_DIAMOND_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.blue_diamond.death"));
	public static final SoundEvent AQUAMARINE_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.aquamarine.living"));
	public static final SoundEvent AQUAMARINE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.aquamarine.hurt"));
	public static final SoundEvent AQUAMARINE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.aquamarine.obey"));
	public static final SoundEvent AQUAMARINE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.aquamarine.death"));
	public static final SoundEvent GARNET_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.garnet.death"));
	public static final SoundEvent GARNET_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.garnet.hurt"));
	public static final SoundEvent GARNET_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.garnet.obey"));
	public static final SoundEvent HESSONITE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.death"));
	public static final SoundEvent HESSONITE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.hurt"));
	public static final SoundEvent HESSONITE_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.living"));
	public static final SoundEvent HESSONITE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.obey"));
	public static final SoundEvent HESSONITE_TELEPORT_START = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.teleport.start"));
	public static final SoundEvent HESSONITE_TELEPORT_END = new SoundEvent(new ResourceLocation("ndbkagic:entities.hessonite.teleport.end"));
	public static final SoundEvent MALACHITE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.malachite.death"));
	public static final SoundEvent MALACHITE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.malachite.hurt"));
	public static final SoundEvent MALACHITE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.malachite.obey"));
	public static final SoundEvent RHODONITE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.rhodonite.death"));
	public static final SoundEvent RHODONITE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.rhodonite.hurt"));
	public static final SoundEvent RHODONITE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.rhodonite.obey"));
	public static final SoundEvent RUTILE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.rutile.death"));
	public static final SoundEvent RUTILE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.rutile.hurt"));
	public static final SoundEvent RUTILE_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.rutile.living"));
	public static final SoundEvent RUTILE_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.rutile.obey"));
	public static final SoundEvent TOPAZ_STEP = new SoundEvent(new ResourceLocation("ndbkagic:entities.topaz.step"));
	public static final SoundEvent TOPAZ_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.topaz.obey"));
	public static final SoundEvent TOPAZ_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.topaz.death"));
	public static final SoundEvent ZIRCON_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.zircon.death"));
	public static final SoundEvent ZIRCON_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.zircon.hurt"));
	public static final SoundEvent ZIRCON_OBEY = new SoundEvent(new ResourceLocation("ndbkagic:entities.zircon.obey"));

	public static final SoundEvent STEVEN_HELLO = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.hello"));
	public static final SoundEvent STEVEN_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.living"));
	public static final SoundEvent STEVEN_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.hurt"));
	public static final SoundEvent STEVEN_PROTECT = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.protect"));
	public static final SoundEvent STEVEN_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.death"));
	public static final SoundEvent STEVEN_SNEEZE = new SoundEvent(new ResourceLocation("ndbkagic:entities.steven.sneeze"));
	public static final SoundEvent CONNIE_HELLO = new SoundEvent(new ResourceLocation("ndbkagic:entities.connie.hello"));
	public static final SoundEvent CONNIE_LIVING = new SoundEvent(new ResourceLocation("ndbkagic:entities.connie.living"));
	public static final SoundEvent CONNIE_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.connie.hurt"));
	public static final SoundEvent CONNIE_PROTECT = new SoundEvent(new ResourceLocation("ndbkagic:entities.connie.protect"));
	public static final SoundEvent CONNIE_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.connie.death"));

	public static final SoundEvent CORRUPTED_QUARTZ_AMBIENT = new SoundEvent(new ResourceLocation("ndbkagic:entities.corrupted_quartz.living"));
	public static final SoundEvent CORRUPTED_QUARTZ_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.corrupted_quartz.hurt"));
	public static final SoundEvent CORRUPTED_QUARTZ_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.corrupted_quartz.death"));
	public static final SoundEvent TONGUE_MONSTER_AMBIENT = new SoundEvent(new ResourceLocation("ndbkagic:entities.tongue_monster.living"));
	public static final SoundEvent TONGUE_MONSTER_HURT = new SoundEvent(new ResourceLocation("ndbkagic:entities.tongue_monster.hurt"));
	public static final SoundEvent TONGUE_MONSTER_DEATH = new SoundEvent(new ResourceLocation("ndbkagic:entities.tongue_monster.death"));

	public static final SoundEvent WARP_PAD = new SoundEvent(new ResourceLocation("ndbkagic:blocks.warp_pad"));

	public static final SoundEvent[] JAM_BUDS_SONG_PARTS = new SoundEvent[40];
	
	public static void registerSounds(RegistryEvent.Register<SoundEvent> event) {
		ModSounds.registerSound(ModSounds.RECORD_LITTLE_PERIDOT, new ResourceLocation("ndbkagic:records.little_peridot"), event);
		ModSounds.registerSound(ModSounds.RECORD_ROSES_FOUNTAIN, new ResourceLocation("ndbkagic:records.roses_fountain"), event);
		ModSounds.registerSound(ModSounds.RECORD_LAPIS_FLIGHT, new ResourceLocation("ndbkagic:records.lapis_flight"), event);
		ModSounds.registerSound(ModSounds.RECORD_THE_BREAKING_POINT, new ResourceLocation("ndbkagic:records.the_breaking_point"), event);
		ModSounds.registerSound(ModSounds.RECORD_DUEL_OF_THE_QUARTZ, new ResourceLocation("ndbkagic:records.duel_of_the_quartz"), event);
		ModSounds.registerSound(ModSounds.RECORD_YELLOW_DIAMOND, new ResourceLocation("ndbkagic:records.yellow_diamond"), event);
		ModSounds.registerSound(ModSounds.RECORD_BLUE_DIAMOND, new ResourceLocation("ndbkagic:records.blue_diamond"), event);
		ModSounds.registerSound(ModSounds.RECORD_WHATS_THE_USE_OF_FEELING_BLUE, new ResourceLocation("ndbkagic:records.whats_the_use_of_feeling_blue"), event);
		ModSounds.registerSound(ModSounds.RECORD_HEAVEN_BEETLE, new ResourceLocation("ndbkagic:records.heaven_beetle"), event);
		ModSounds.registerSound(ModSounds.RECORD_DEFECTIVE, new ResourceLocation("ndbkagic:records.defective"), event);
		ModSounds.registerSound(ModSounds.RECORD_GEM_SHARDS, new ResourceLocation("ndbkagic:records.gem_shards"), event);
		ModSounds.registerSound(ModSounds.RECORD_HEART_OF_THE_PYRAMID, new ResourceLocation("ndbkagic:records.pyramid"), event);
		ModSounds.registerSound(ModSounds.RECORD_LOVE_LIKE_YOU, new ResourceLocation("ndbkagic:records.love_like_you"), event);
		ModSounds.registerSound(ModSounds.BLOCK_GEM_SEED_HATCH, new ResourceLocation("ndbkagic:blocks.gem_seed_hatch"), event);
		ModSounds.registerSound(ModSounds.BLOCK_INJECTOR_OPEN, new ResourceLocation("ndbkagic:blocks.injector_open"), event);
		ModSounds.registerSound(ModSounds.BLOCK_INJECTOR_CLOSE, new ResourceLocation("ndbkagic:blocks.injector_close"), event);
		ModSounds.registerSound(ModSounds.BLOCK_INJECTOR_FIRE, new ResourceLocation("ndbkagic:blocks.injector_fire"), event);
		ModSounds.registerSound(ModSounds.GEM_POOF, new ResourceLocation("ndbkagic:entities.gem.poof"), event);
		ModSounds.registerSound(ModSounds.GEM_SHATTER, new ResourceLocation("ndbkagic:entities.gem.shatter"), event);
		ModSounds.registerSound(ModSounds.SLAG_EAT, new ResourceLocation("ndbkagic:entities.slag.eat"), event);
		ModSounds.registerSound(ModSounds.SLAG_LIVING, new ResourceLocation("ndbkagic:entities.slag.living"), event);
		ModSounds.registerSound(ModSounds.PEPO_LIVING, new ResourceLocation("ndbkagic:entities.pepo.living"), event);
		ModSounds.registerSound(ModSounds.RUBY_LIVING, new ResourceLocation("ndbkagic:entities.ruby.living"), event);
		ModSounds.registerSound(ModSounds.RUBY_HURT, new ResourceLocation("ndbkagic:entities.ruby.hurt"), event);
		ModSounds.registerSound(ModSounds.RUBY_OBEY, new ResourceLocation("ndbkagic:entities.ruby.obey"), event);
		ModSounds.registerSound(ModSounds.RUBY_DEATH, new ResourceLocation("ndbkagic:entities.ruby.death"), event);
		ModSounds.registerSound(ModSounds.RUBY_EXPLODE, new ResourceLocation("ndbkagic:entities.ruby.explode"), event);
		ModSounds.registerSound(ModSounds.RUBY_COMBINE, new ResourceLocation("kagic.entities.ruby.combine"), event);
		ModSounds.registerSound(ModSounds.SAPPHIRE_LIVING, new ResourceLocation("ndbkagic:entities.sapphire.living"), event);
		ModSounds.registerSound(ModSounds.SAPPHIRE_HURT, new ResourceLocation("ndbkagic:entities.sapphire.hurt"), event);
		ModSounds.registerSound(ModSounds.SAPPHIRE_OBEY, new ResourceLocation("ndbkagic:entities.sapphire.obey"), event);
		ModSounds.registerSound(ModSounds.SAPPHIRE_DEATH, new ResourceLocation("ndbkagic:entities.sapphire.death"), event);
		ModSounds.registerSound(ModSounds.PADPARADSCHA_LIVING, new ResourceLocation("ndbkagic:entities.padparadscha.living"), event);
		ModSounds.registerSound(ModSounds.PERIDOT_LIVING, new ResourceLocation("ndbkagic:entities.peridot.living"), event);
		ModSounds.registerSound(ModSounds.PERIDOT_HURT, new ResourceLocation("ndbkagic:entities.peridot.hurt"), event);
		ModSounds.registerSound(ModSounds.PERIDOT_OBEY, new ResourceLocation("ndbkagic:entities.peridot.obey"), event);
		ModSounds.registerSound(ModSounds.PERIDOT_DEATH, new ResourceLocation("ndbkagic:entities.peridot.death"), event);
		ModSounds.registerSound(ModSounds.PEARL_HURT, new ResourceLocation("ndbkagic:entities.pearl.hurt"), event);
		ModSounds.registerSound(ModSounds.PEARL_OBEY, new ResourceLocation("ndbkagic:entities.pearl.obey"), event);
		ModSounds.registerSound(ModSounds.PEARL_DEATH, new ResourceLocation("ndbkagic:entities.pearl.death"), event);
		ModSounds.registerSound(ModSounds.PEARL_SING, new ResourceLocation("ndbkagic:entities.pearl.sing"), event);
		ModSounds.registerSound(ModSounds.PEARL_WEIRD, new ResourceLocation("ndbkagic:entities.pearl.weird"), event);
		ModSounds.registerSound(ModSounds.BISMUTH_HURT, new ResourceLocation("ndbkagic:entities.bismuth.hurt"), event);
		ModSounds.registerSound(ModSounds.BISMUTH_OBEY, new ResourceLocation("ndbkagic:entities.bismuth.obey"), event);
		ModSounds.registerSound(ModSounds.BISMUTH_DEATH, new ResourceLocation("ndbkagic:entities.bismuth.death"), event);
		ModSounds.registerSound(ModSounds.JASPER_HURT, new ResourceLocation("ndbkagic:entities.jasper.hurt"), event);
		ModSounds.registerSound(ModSounds.JASPER_OBEY, new ResourceLocation("ndbkagic:entities.jasper.obey"), event);
		ModSounds.registerSound(ModSounds.JASPER_DEATH, new ResourceLocation("ndbkagic:entities.jasper.death"), event);
		ModSounds.registerSound(ModSounds.AMETHYST_HURT, new ResourceLocation("ndbkagic:entities.amethyst.hurt"), event);
		ModSounds.registerSound(ModSounds.AMETHYST_OBEY, new ResourceLocation("ndbkagic:entities.amethyst.obey"), event);
		ModSounds.registerSound(ModSounds.AMETHYST_DEATH, new ResourceLocation("ndbkagic:entities.amethyst.death"), event);
		ModSounds.registerSound(ModSounds.ROSE_QUARTZ_HURT, new ResourceLocation("ndbkagic:entities.rose_quartz.hurt"), event);
		ModSounds.registerSound(ModSounds.ROSE_QUARTZ_OBEY, new ResourceLocation("ndbkagic:entities.rose_quartz.obey"), event);
		ModSounds.registerSound(ModSounds.CARNELIAN_DEATH, new ResourceLocation("ndbkagic:entities.rose_quartz.death"), event);
		ModSounds.registerSound(ModSounds.CARNELIAN_HURT, new ResourceLocation("ndbkagic:entities.carnelian.hurt"), event);
		ModSounds.registerSound(ModSounds.CARNELIAN_OBEY, new ResourceLocation("ndbkagic:entities.carnelian.obey"), event);
		ModSounds.registerSound(ModSounds.ROSE_QUARTZ_DEATH, new ResourceLocation("ndbkagic:entities.carnelian.death"), event);
		ModSounds.registerSound(ModSounds.LAPIS_LAZULI_HURT, new ResourceLocation("ndbkagic:entities.lapis_lazuli.hurt"), event);
		ModSounds.registerSound(ModSounds.LAPIS_LAZULI_OBEY, new ResourceLocation("ndbkagic:entities.lapis_lazuli.obey"), event);
		ModSounds.registerSound(ModSounds.LAPIS_LAZULI_DEATH, new ResourceLocation("ndbkagic:entities.lapis_lazuli.death"), event);
		ModSounds.registerSound(ModSounds.AGATE_HURT, new ResourceLocation("ndbkagic:entities.agate.hurt"), event);
		ModSounds.registerSound(ModSounds.AGATE_OBEY, new ResourceLocation("ndbkagic:entities.agate.obey"), event);
		ModSounds.registerSound(ModSounds.AGATE_DEATH, new ResourceLocation("ndbkagic:entities.agate.death"), event);
		ModSounds.registerSound(ModSounds.YELLOW_DIAMOND_INTRO, new ResourceLocation("ndbkagic:entities.yellow_diamond.intro"), event);
		ModSounds.registerSound(ModSounds.YELLOW_DIAMOND_OUTRO, new ResourceLocation("ndbkagic:entities.yellow_diamond.outro"), event);
		ModSounds.registerSound(ModSounds.YELLOW_DIAMOND_LIVING, new ResourceLocation("ndbkagic:entities.yellow_diamond.living"), event);
		ModSounds.registerSound(ModSounds.YELLOW_DIAMOND_HURT, new ResourceLocation("ndbkagic:entities.yellow_diamond.hurt"), event);
		ModSounds.registerSound(ModSounds.YELLOW_DIAMOND_DEATH, new ResourceLocation("ndbkagic:entities.yellow_diamond.death"), event);
		ModSounds.registerSound(ModSounds.BLUE_DIAMOND_INTRO, new ResourceLocation("ndbkagic:entities.blue_diamond.intro"), event);
		ModSounds.registerSound(ModSounds.BLUE_DIAMOND_OUTRO, new ResourceLocation("ndbkagic:entities.blue_diamond.outro"), event);
		ModSounds.registerSound(ModSounds.BLUE_DIAMOND_LIVING, new ResourceLocation("ndbkagic:entities.blue_diamond.living"), event);
		ModSounds.registerSound(ModSounds.BLUE_DIAMOND_HURT, new ResourceLocation("ndbkagic:entities.blue_diamond.hurt"), event);
		ModSounds.registerSound(ModSounds.BLUE_DIAMOND_DEATH, new ResourceLocation("ndbkagic:entities.blue_diamond.death"), event);
		ModSounds.registerSound(ModSounds.AQUAMARINE_LIVING, new ResourceLocation("ndbkagic:entities.aquamarine.living"), event);
		ModSounds.registerSound(ModSounds.AQUAMARINE_HURT, new ResourceLocation("ndbkagic:entities.aquamarine.hurt"), event);
		ModSounds.registerSound(ModSounds.AQUAMARINE_OBEY, new ResourceLocation("ndbkagic:entities.aquamarine.obey"), event);
		ModSounds.registerSound(ModSounds.AQUAMARINE_DEATH, new ResourceLocation("ndbkagic:entities.aquamarine.death"), event);
		ModSounds.registerSound(ModSounds.GARNET_DEATH, new ResourceLocation("ndbkagic:entities.garnet.death"), event);
		ModSounds.registerSound(ModSounds.GARNET_HURT, new ResourceLocation("ndbkagic:entities.garnet.hurt"), event);
		ModSounds.registerSound(ModSounds.GARNET_OBEY, new ResourceLocation("ndbkagic:entities.garnet.obey"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_DEATH, new ResourceLocation("ndbkagic:entities.hessonite.death"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_HURT, new ResourceLocation("ndbkagic:entities.hessonite.hurt"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_LIVING, new ResourceLocation("ndbkagic:entities.hessonite.living"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_OBEY, new ResourceLocation("ndbkagic:entities.hessonite.obey"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_TELEPORT_START, new ResourceLocation("ndbkagic:entities.hessonite.teleport.start"), event);
		ModSounds.registerSound(ModSounds.HESSONITE_TELEPORT_END, new ResourceLocation("ndbkagic:entities.hessonite.teleport.end"), event);
		ModSounds.registerSound(ModSounds.MALACHITE_DEATH, new ResourceLocation("ndbkagic:entities.malachite.death"), event);
		ModSounds.registerSound(ModSounds.MALACHITE_HURT, new ResourceLocation("ndbkagic:entities.malachite.hurt"), event);
		ModSounds.registerSound(ModSounds.MALACHITE_OBEY, new ResourceLocation("ndbkagic:entities.malachite.obey"), event);
		ModSounds.registerSound(ModSounds.RHODONITE_DEATH, new ResourceLocation("ndbkagic:entities.rhodonite.death"), event);
		ModSounds.registerSound(ModSounds.RHODONITE_HURT, new ResourceLocation("ndbkagic:entities.rhodonite.hurt"), event);
		ModSounds.registerSound(ModSounds.RHODONITE_OBEY, new ResourceLocation("ndbkagic:entities.rhodonite.obey"), event);
		ModSounds.registerSound(ModSounds.RUTILE_DEATH, new ResourceLocation("ndbkagic:entities.rutile.death"), event);
		ModSounds.registerSound(ModSounds.RUTILE_HURT, new ResourceLocation("ndbkagic:entities.rutile.hurt"), event);
		ModSounds.registerSound(ModSounds.RUTILE_LIVING, new ResourceLocation("ndbkagic:entities.rutile.living"), event);
		ModSounds.registerSound(ModSounds.RUTILE_OBEY, new ResourceLocation("ndbkagic:entities.rutile.obey"), event);
		ModSounds.registerSound(ModSounds.TOPAZ_STEP, new ResourceLocation("ndbkagic:entities.topaz.step"), event);
		ModSounds.registerSound(ModSounds.TOPAZ_OBEY, new ResourceLocation("ndbkagic:entities.topaz.obey"), event);
		ModSounds.registerSound(ModSounds.TOPAZ_DEATH, new ResourceLocation("ndbkagic:entities.topaz.death"), event);
		ModSounds.registerSound(ModSounds.ZIRCON_DEATH, new ResourceLocation("ndbkagic:entities.zircon.death"), event);
		ModSounds.registerSound(ModSounds.ZIRCON_HURT, new ResourceLocation("ndbkagic:entities.zircon.hurt"), event);
		ModSounds.registerSound(ModSounds.ZIRCON_OBEY, new ResourceLocation("ndbkagic:entities.zircon.obey"), event);
		ModSounds.registerSound(ModSounds.STEVEN_HELLO, new ResourceLocation("ndbkagic:entities.steven.hello"), event);
		ModSounds.registerSound(ModSounds.STEVEN_LIVING, new ResourceLocation("ndbkagic:entities.steven.living"), event);
		ModSounds.registerSound(ModSounds.STEVEN_HURT, new ResourceLocation("ndbkagic:entities.steven.hurt"), event);
		ModSounds.registerSound(ModSounds.STEVEN_PROTECT, new ResourceLocation("ndbkagic:entities.steven.protect"), event);
		ModSounds.registerSound(ModSounds.STEVEN_DEATH, new ResourceLocation("ndbkagic:entities.steven.death"), event);
		ModSounds.registerSound(ModSounds.STEVEN_SNEEZE, new ResourceLocation("ndbkagic:entities.steven.sneeze"), event);
		ModSounds.registerSound(ModSounds.CONNIE_HELLO, new ResourceLocation("ndbkagic:entities.connie.hello"), event);
		ModSounds.registerSound(ModSounds.CONNIE_LIVING, new ResourceLocation("ndbkagic:entities.connie.living"), event);
		ModSounds.registerSound(ModSounds.CONNIE_HURT, new ResourceLocation("ndbkagic:entities.connie.hurt"), event);
		ModSounds.registerSound(ModSounds.CONNIE_PROTECT, new ResourceLocation("ndbkagic:entities.connie.protect"), event);
		ModSounds.registerSound(ModSounds.CONNIE_DEATH, new ResourceLocation("ndbkagic:entities.connie.death"), event);
		ModSounds.registerSound(ModSounds.CORRUPTED_QUARTZ_AMBIENT, new ResourceLocation("ndbkagic:entities.corrupted_quartz.living"), event);
		ModSounds.registerSound(ModSounds.CORRUPTED_QUARTZ_HURT, new ResourceLocation("ndbkagic:entities.corrupted_quartz.hurt"), event);
		ModSounds.registerSound(ModSounds.CORRUPTED_QUARTZ_DEATH, new ResourceLocation("ndbkagic:entities.corrupted_quartz.death"), event);
		ModSounds.registerSound(ModSounds.TONGUE_MONSTER_AMBIENT, new ResourceLocation("ndbkagic:entities.tongue_monster.living"), event);
		ModSounds.registerSound(ModSounds.TONGUE_MONSTER_HURT, new ResourceLocation("ndbkagic:entities.tongue_monster.hurt"), event);
		ModSounds.registerSound(ModSounds.TONGUE_MONSTER_DEATH, new ResourceLocation("ndbkagic:entities.tongue_monster.death"), event);
		ModSounds.registerSound(ModSounds.WARP_PAD, new ResourceLocation(KAGIC.MODID, "warp_pad"), event);
		for (int i = 0; i < ModSounds.JAM_BUDS_SONG_PARTS.length; ++i) {
			int part = i + 1;
			ModSounds.JAM_BUDS_SONG_PARTS[i] = new SoundEvent(new ResourceLocation("ndbkagic:songs.jam_buds_" + part));
			ModSounds.registerSound(ModSounds.JAM_BUDS_SONG_PARTS[i], new ResourceLocation("ndbkagic:songs.jam_buds_" + part), event);
		}
	}

	private static void registerSound(SoundEvent sound, ResourceLocation location, RegistryEvent.Register<SoundEvent> event) {
		sound.setRegistryName(location);
		event.getRegistry().register(sound);
	}
}
